Repository prgrms-fe-devcourse/NFE1_2_3_Yummy, pull requests merged in 2024-10, with the labels that each got.

#6 🚚 [Chore] 프론트 폴더 변경 / 백엔드 폴더 생성
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
  backend/yarn.lock
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/.gitkeep
  frontend/src/App.tsx
  frontend/src/apis/api.ts
  frontend/src/assets/.gitkeep
  frontend/src/components/.gitkeep
  frontend/src/hooks/.gitkeep
  frontend/src/layouts/.gitkeep
  frontend/src/main.tsx
  frontend/src/pages/.gitkeep
  frontend/src/store/.gitkeep
  frontend/src/typings/vite-env.d.ts
  frontend/src/utils/.gitkeep
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 🍏 프론트엔드, 🍎 백엔드

#9 Feat/#3 헤더, 푸터 컴포넌트 완료
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/Logo.png
  frontend/public/Yum문구.png
  frontend/src/App.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/pages/LogInPage.tsx
  frontend/src/pages/SignInPage.tsx
  frontend/src/pages/WritingPage.tsx
  frontend/src/typings/react-draft-wysiwyg.d.ts
  frontend/vite.config.ts
Labels: 🍏 프론트엔드

#10 [Feat]게시글 CRUD 기능 구현
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/main.ts
  backend/src/post/dto/create-post.dto.ts
  backend/src/post/dto/update-post.dto.ts
  backend/src/post/entities/post.entity.ts
  backend/src/post/entities/post.schema.ts
  backend/src/post/post.controller.spec.ts
  backend/src/post/post.controller.ts
  backend/src/post/post.module.ts
  backend/src/post/post.service.spec.ts
  backend/src/post/post.service.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/yarn.lock
Labels: 🍎 백엔드

#16 Feat/#12 글 작성 페이지
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/DraftEditor.tsx
  frontend/src/components/Footer.tsx
  frontend/src/pages/WritingPage.tsx
Labels: 🍏 프론트엔드

#14 [Feat] 마이페이지 마크업
  frontend/package-lock.json
  frontend/package.json
  frontend/public/.gitkeep
  frontend/src/App.tsx
  frontend/src/components/.gitkeep
  frontend/src/components/UserProfileCard/index.tsx
  frontend/src/components/UserProfileCard/style.ts
  frontend/src/components/UserProfileModal/index.tsx
  frontend/src/components/UserProfileModal/style.ts
  frontend/src/index.css
  frontend/src/layouts/.gitkeep
  frontend/src/layouts/pageLayout/index.tsx
  frontend/src/layouts/pageLayout/style.ts
  frontend/src/main.tsx
  frontend/src/pages/.gitkeep
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyPage/style.ts
  frontend/src/utils/.gitkeep
Labels: 🍏 프론트엔드

#18 Feat/#15
  frontend/src/App.tsx
  frontend/src/components/CommentCard/index.tsx
  frontend/src/components/CommentCard/style.ts
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/style.ts
  frontend/src/components/LikeButton/index.tsx
  frontend/src/components/LikeButton/style.ts
  frontend/src/components/PostCommentContainer/index.tsx
  frontend/src/components/PostContainer/index.tsx
  frontend/src/components/PostPagePostCard/index.tsx
  frontend/src/components/PostPagePostCard/style.ts
  frontend/src/components/UserProfileCard/index.tsx
  frontend/src/components/UserProfileCard/style.ts
  frontend/src/pages/MyPage/style.ts
  frontend/src/pages/PostPage/index.tsx
  frontend/src/pages/PostPage/style.ts
  frontend/src/utils/formatDate.ts
Labels: 🍏 프론트엔드

#21 [Feat]댓글 CRUD api 구현
  backend/src/app.module.ts
  backend/src/comment/comment.controller.spec.ts
  backend/src/comment/comment.controller.ts
  backend/src/comment/comment.module.ts
  backend/src/comment/comment.service.spec.ts
  backend/src/comment/comment.service.ts
  backend/src/comment/dto/create-comment.dto.ts
  backend/src/comment/dto/update-comment.dto.ts
  backend/src/comment/entities/comment.schema.ts
  backend/src/main.ts
  backend/src/post/entities/post.entity.ts
  backend/src/post/post.controller.ts
Labels: 🍎 백엔드

#22 Feat/#19
  frontend/src/App.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/components/SearchPageInput/index.tsx
  frontend/src/components/SearchPageInput/style.tsx
  frontend/src/components/SearchPageNav/index.tsx
  frontend/src/components/SearchPageNav/style.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/style.ts
Labels: 🍏 프론트엔드

#24 Feat/#17 글 작성 페이지 완료 - 이미지 업로드 구현
  frontend/src/components/NavBar.tsx
  frontend/src/components/WritingPageComponents/DraftEditor.tsx
  frontend/src/components/WritingPageComponents/ImageUploader.tsx
  frontend/src/main.tsx
  frontend/src/pages/LogInPage.tsx
  frontend/src/pages/SignInPage.tsx
  frontend/src/pages/WritingPage.tsx
  frontend/vite.config.ts
Labels: 🍏 프론트엔드

#27 Feat/#23
  frontend/src/App.tsx
  frontend/src/components/CommentCard/index.tsx
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/LikeButton/index.tsx
  frontend/src/components/SearchPageNav/index.tsx
  frontend/src/components/SearchPageNav/style.ts
  frontend/src/components/UserEditModal/index.tsx
  frontend/src/components/UserEditModal/style.ts
  frontend/src/components/UserProfileCard/index.tsx
  frontend/src/components/UserProfileModal/index.tsx
  frontend/src/hooks/useNavigateTo.ts
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/utils/mockPosts.ts
Labels: 🍏 프론트엔드

#30 [Fix] 카테고리가 숫자로 변환되는 오류 수정
  frontend/src/pages/WritingPage.tsx
Labels: 🍏 프론트엔드

#29 [Feat]회원가입 로직 구현(JWT) / 인증 관련 로직 수정
  .vscode/settings.json
  backend/.gitignore
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt-auth.guard.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/comment/comment.controller.spec.ts
  backend/src/comment/comment.controller.ts
  backend/src/comment/comment.module.ts
  backend/src/comment/comment.service.spec.ts
  backend/src/comment/comment.service.ts
  backend/src/comment/dto/create-comment.dto.ts
  backend/src/comment/dto/update-comment.dto.ts
  backend/src/comment/entities/comment.schema.ts
  backend/src/main.ts
  backend/src/post/entities/post.schema.ts
  backend/src/post/post.controller.spec.ts
  backend/src/post/post.controller.ts
  backend/src/post/post.service.spec.ts
  backend/src/post/post.service.ts
  backend/src/users/dto/create-user.dto.ts
  backend/src/users/dto/login-user.dto.ts
  backend/src/users/schemas/user.schema.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  backend/yarn.lock
Labels: 🍎 백엔드

#34 [Fix]포스트 댓글 조회 시, 빈 배열 반환하는 문제 해결
  backend/src/comment/comment.controller.ts
  backend/src/comment/comment.service.ts
Labels: 🍎 백엔드

#32 Feat/#2
  frontend/src/App.tsx
  frontend/src/apis/postService.ts
  frontend/src/components/CategoryButton.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/components/TopPost.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/utils/mockPosts.ts
Labels: 🍏 프론트엔드

#35 [Feat]회원 정보 수정 로직 구현 / Post, Comment가 User 객체 참조하도록 수정
  backend/.gitignore
  backend/src/comment/comment.controller.ts
  backend/src/comment/comment.service.ts
  backend/src/comment/entities/comment.schema.ts
  backend/src/main.ts
  backend/src/post/entities/post.schema.ts
  backend/src/post/post.service.ts
  backend/src/users/dto/update-user.dto.ts
  backend/src/users/schemas/user.schema.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: 🍎 백엔드

#37 [Feat] 페이지별 api 연동 및 리팩토링
  backend/package-lock.json
  backend/yarn.lock
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/ky.ts
  frontend/src/apis/postService.ts
  frontend/src/components/CategoryButton.tsx
  frontend/src/components/CommentCard/index.tsx
  frontend/src/components/CommentCard/style.ts
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/components/PostCommentContainer/index.tsx
  frontend/src/components/PostPagePostCard/index.tsx
  frontend/src/components/PostPagePostCard/style.ts
  frontend/src/components/PostSideButton/index.tsx
  frontend/src/components/PostSideButton/style.ts
  frontend/src/components/SearchPageInput/index.tsx
  frontend/src/components/TopPost.tsx
  frontend/src/components/UserEditModal/index.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PostPage/index.tsx
  frontend/src/pages/PostPage/style.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/typings/db.ts
  frontend/src/utils/Model/commentModel.ts
  frontend/src/utils/formatDate.ts
Labels: 🍏 프론트엔드

#40 [Feat/#2] 메인페이지 CSS 수정
  frontend/src/components/CategoryButton.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
Labels: 🍏 프론트엔드

#49 [Feat] 서치페이지 api 연동중
  frontend/src/apis/postService.ts
  frontend/src/components/CategoryButton.tsx
  frontend/src/components/PostContainer/index.tsx
  frontend/src/components/PostPagePostCard/style.ts
  frontend/src/components/SearchContainer/index.tsx
  frontend/src/components/SearchContainer/style.ts
  frontend/src/components/SearchPageInput/index.tsx
  frontend/src/hooks/useDebounce.ts
  frontend/src/main.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/style.ts
  frontend/src/typings/db.ts
Labels: 🍏 프론트엔드

#48 [Feat]User ID 기반 유저 정보 조회 API 구현
  backend/src/post/post.service.ts
  backend/src/users/schemas/user.schema.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: 🍎 백엔드

#52 [Feat/#2] 메인 페이지 UI 수정
  frontend/src/components/CategoryButton.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/components/TopPost.tsx
  frontend/src/pages/MainPage.tsx
Labels: 🍏 프론트엔드

#53 [Feat]로그인 반환값에 user 객체를 추가
  backend/src/auth/auth.service.ts
Labels: 🍎 백엔드

#54 [Feat] 서치 페이지 API 및 페이지네이션 처리
  frontend/src/apis/postService.ts
  frontend/src/components/SearchContainer/index.tsx
  frontend/src/components/SearchContainer/style.ts
  frontend/src/components/SearchPageInput/index.tsx
  frontend/src/components/SearchPageInput/style.tsx
  frontend/src/components/SearchPageNav/style.ts
  frontend/src/components/SearchResultContainer/index.tsx
  frontend/src/components/SearchResultContainer/style.ts
  frontend/src/pages/SearchPage/index.tsx
  frontend/src/pages/SearchPage/style.ts
Labels: 🍏 프론트엔드

#57 [Feat]좋아요 로직 구현
  backend/src/comment/entities/comment.schema.ts
  backend/src/post/entities/post.schema.ts
  backend/src/post/post.controller.ts
  backend/src/post/post.service.ts
  backend/src/users/schemas/user.schema.ts
Labels: 🍎 백엔드

#56 [Feat/#25] UI 수정, 리팩토링, 아바타 사진 연동 등등
  frontend/src/components/NavBar.tsx
  frontend/src/components/WritingPageComponents/ImageUploader.tsx
  frontend/src/pages/LogInPage.tsx
  frontend/src/pages/SignInPage.tsx
  frontend/src/pages/WritingPage.tsx
  package-lock.json
  package.json
Labels: 🍏 프론트엔드

#62 [Feat]참조 데이터 일괄 삭제 기능 구현 / Atlas 연동
  backend/package-lock.json
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/post/entities/post.schema.ts
  backend/src/post/post.module.ts
  backend/src/post/post.service.ts
  backend/yarn.lock
Labels: 🍎 백엔드

#65 [Fix]NaN 값으로 인한 로그인 오류 문제 해결
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/users/schemas/user.schema.ts
Labels: 🍎 백엔드

#66 [Feat]dangerouslySetInnerHTML 대안 검토 및 구현
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PostCard.tsx
  frontend/src/components/PostPagePostCard/index.tsx
  frontend/src/components/TopPost.tsx
  frontend/src/pages/MainPage.tsx
Labels: 🍏 프론트엔드

#67 [FEAT] 좋아요 API 연동 및 댓글 CRUD 작업완료
  frontend/src/apis/postService.ts
  frontend/src/components/CommentCard/index.tsx
  frontend/src/components/CommentInput/index.tsx
  frontend/src/components/CommentInput/style.ts
  frontend/src/components/DeleteModal/index.tsx
  frontend/src/components/LikeButton/index.tsx
  frontend/src/components/LikeButton/style.ts
  frontend/src/components/PostContainer/index.tsx
  frontend/src/components/PostSideButton/index.tsx
  frontend/src/components/UserEditModal/index.tsx
  frontend/src/hooks/useDebounce.ts
  frontend/src/pages/PostPage/index.tsx
  frontend/src/store/usePostModal.ts
  frontend/src/typings/db.ts
  frontend/src/utils/Model/commentModel.ts
  frontend/src/utils/constants.ts
Labels: 🍏 프론트엔드
